steps:
  # Bước 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ingest-taxi-data:$SHORT_SHA',
      '.'
    ]

  # Bước 2: Push image lên Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ingest-taxi-data:$SHORT_SHA'
    ]

  # Bước 3: Tạo Release trên Cloud Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'deploy', 'releases', 'create', 'rel-$SHORT_SHA',
        '--delivery-pipeline', 'taxi-ingest-pipeline',
        '--region', 'us-east1',
        '--images', 'ingest-taxi-image=us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ingest-taxi-data:$SHORT_SHA'
      ]

options:
  logging: CLOUD_LOGGING_ONLY